
[build]
  functions = "netlify/functions"
  publish = "."
[functions]
  node_bundler = "esbuild"
[[redirects]]
  from = "/api/site-config"
  to = "/.netlify/functions/site-config"
  status = 200
  force = true
[[redirects]]
  from = "/api/youtube-latest"
  to = "/.netlify/functions/youtube-latest"
  status = 200
  force = true
